### Optional: Default log level
global_level = 'info'

### Optional: specify a regular expression to suppress all messages that don't match
# global_pattern = 'foo'
global_pattern = '.*(songbird::driver|tracing::span).*'

### Specific log levels per module are optionally defined in this section
[modules]
'osubelgiumbot' = 'debug'
'sqlx' = 'warn'
